### ISSUE TITLE
Caching doesn't work for CI builds?

### ISSUE THREAD

**Issue by igrayson** [grammarly/rocker#108]
Hi team,

We use CircleCI for continuous integration. To speed up docker builds (cache hits), I've tried:
1. `docker save/load` to/from a `.tar` file, which CircleCI copies between builds.
2. `docker push/pull` to/from our repository.

Using either technique, rocker doesn't manage any cache hits, and always rebuilds the image entirely. We do `MOUNT` node_modules, so the `npm install` is quicker, but I notice this: still requires us to pessimistically `apk get` dependencies for building native modules; and more importantly causes each build to produce an image which shares no layers with the previous build, causing deployments to slow down as they re-fetch different layers containing ~identical `node_modules`.

CircleCI uses the btrfs driver.

Is there any workaround?

The following docker issues seem related:
- https://github.com/docker/docker/issues/18179: docker 1.8.2 stopped producing stable ImageIDs through `docker push/pull`.
- https://github.com/docker/docker/pull/17924: docker 1.10 reworked content addressing, such that layers are no longer always guaranteed to be stored as layers.
- https://github.com/docker/docker/issues/20668: describes the behavior change in 1.10 again.

**Comment by igrayson** [comment]
Our current workaround: use `docker save/load` with docker 1.9.1. Updating to 1.10 breaks this workaround.

**Comment by ybogdanov** [comment]
You should also keep rocker cache directory https://github.com/grammarly/rocker/blob/master/main.go#L129 to use the images you have saved and loaded.

Regarding Docker 1.10. How about to re-engineer your builds to leverage from Rocker's primitives such as MOUNT?

**Comment by igrayson** [comment]
Thanks for the reply.

As I described, we _do_ use `MOUNT`, but it's still a ~1 minute cost to re-evaluate our `RUN npm install` line, which looks like this:

```
RUN apk add --no-cache python make gcc g++ findutils postgresql-dev=${PG_VERSION} \
  && npm prune \
  && npm install \
  && apk del --purge python make gcc g++ findutils postgresql-dev
```

We are caching our `~/.rocker_cache` folder.

**Comment by kreisys** [comment]
@igrayson how exactly did you make save/load work?
I'm trying to use save/load with 1.9.1 and it doesn't work:
after loading the tar image from the previous CI run, rocker build would (redundantly) download the first FROM image and continue building the entire thing with no cache hits whatsoever.

**Comment by igrayson** [comment]
I'm not sure this is the fix, but our save script also explicitly saves the `FROM` image.

**Comment by kreisys** [comment]
@igrayson that did the trick thanks!

**Comment by ybogdanov** [comment]
Closing this issue as the project is discontinued. See https://github.com/grammarly/rocker/blob/master/README.md
