### ISSUE TITLE
Persistent MOUNT

### ISSUE THREAD

**Issue by IlyaSemenov** [grammarly/rocker#109]
That would be great if `MOUNT` could (optionally) persist between multiple `FROM`. The primary use for that is to provide a mount point for Docker instructions within `ONBUILD` block.

Consider a base Dockerfile:

```
FROM some-image-with-nodejs
ONBUILD COPY package.json /
ONBUILD RUN npm install --production
ONBUILD COPY . /app
```

then `docker build -t node-app .`

and a Rockerfile:

```
MOUNT /root/.npm
FROM node-app
CMD ["nodejs", "/app/entrypoint.js"]
```

Unfortunately, `/root/.npm` will not be mounted, and each `rocker build` will spend a lot of time redownloading npm packages.

I realize that it's probably beyond the scope of what you originally needed, I am leaving this more like an idea for future.

**Comment by tahajahangir** [comment]
Use `ADD` instead of `MOUNT` (or do `cp` after mounting) to retain files in docker images.

**Comment by IlyaSemenov** [comment]
@tahajahangir please read the example `Dockerfile` and `Rockerfile` above. The `FROM` statement atomically dismounts the mounted folder **and** runs all `ONBUILD` statements from the inherited Dockerfile. There's no chance for anything else to kick in.

Also, I obviously don't need the entire `.npm` cache to be persistent in the images.

**Comment by ybogdanov** [comment]
Thanks for requesting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to implement it. Sorry.
