### ISSUE TITLE
Random mount failure when using docker in docker

### ISSUE THREAD

**Issue by aacebedo** [grammarly/rocker#120]
Hi

I am using docker in docker (through sharing the docker.sockl file) to create container in a CI container.
Building a rockerfile within the container randomly fails with a "can't make ... relative to ..." error.

I've found that the issue is coming from the src/dockerclient/matrix.go file in the function ResolveHostPath. The mount array order is not guarantee and an invalid mount (with [] in its name) is processed by the loop. This triggers an error and fails the build.

I am going to issue a PR to solve this.

Regards

**Comment by ybogdanov** [comment]
Please open a PR to merge with `dev` branch.

**Comment by aacebedo** [comment]
done :)
