### ISSUE TITLE
Implement HEALTHCHECK

### ISSUE THREAD

**Issue by ybogdanov** [grammarly/rocker#125]
As specified in the doc https://docs.docker.com/engine/reference/builder/#/healthcheck

**Comment by ybogdanov** [comment]
https://github.com/fsouza/go-dockerclient/issues/551

**Comment by ncuesta** [comment]
Hi @ybogdanov , I see your fsouza/go-dockerclient#559 has been merged into master. Is there an ETA on when this upstream changes will be included in Rocker?

Thanks a lot,

**Comment by ybogdanov** [comment]
@ncuesta #144

**Comment by ncuesta** [comment]
@ybogdanov Awesome, thanks for getting back, I've subscribed to #144 and #145 to keep an eye of changes on those.

Great work guys, I find Rocker really useful!

**Comment by ybogdanov** [comment]
Nice to hear that, @ncuesta

**Comment by ybogdanov** [comment]
Closing this issue as the project is discontinued. See https://github.com/grammarly/rocker/blob/master/README.md
