### ISSUE TITLE
Can't mount host volumes

### ISSUE THREAD

**Issue by raphapr** [grammarly/rocker#131]
Hi

I'm want to use rocker to mount host volumes in Dockerfile during build. However, I'm trying build with a simple Rockerfile and it won't mount. 

my Rockerfile
```
FROM ubuntu:14.04
MOUNT .:/polsar
TAG test
```

rocker build
```
INFO[0000] FROM ubuntu:14.04                 
INFO[0000] | Image sha256:0ccb1                          size=188 MB
INFO[0000] MOUNT .:/polsar                   
INFO[0000] Commit changes                    
INFO[0000] | Not cached                        
INFO[0000] | Created container b26934e5623f (image sha256:0ccb1) 
INFO[0000] | Result image is sha256:a03d6                size=188 MB (+0 B)
INFO[0000] | Removing container b26934e5623f            
INFO[0000] TAG rocker                        
INFO[0000] | Tag sha256:a03d6 -> rocker:latest          
INFO[0000] Cleaning up                       
INFO[0000] Successfully built sha256:a03d6 | final size 188 MB (+0 B from the base image)
```

But after create the container using "docker run -it test" I can't see the host volume mounted in /.

**Comment by ybogdanov** [comment]
Hi @raphapr. The `MOUNT` command is a way to bind a host directory to a container in the build time. It has nothing to do with a container you run after the image is built. That is, `MOUNT` affects only containers executed by `RUN` instructions in your Dockerfile.

**Comment by raphapr** [comment]
Ah, I had not understood the `MOUNT` command. Thanks you for your quick reply @ybogdanov! (:
