### ISSUE TITLE
ATTACH syntax : either the code or the doc is wrong

### ISSUE THREAD

**Issue by hartym** [grammarly/rocker#134]
If I run ATTACH ['/bin/bash'], I get this output:

```
INFO[0000] ATTACH ['/bin/bash']
INFO[0000] | Created container 0adcb13ea525 (image sha256:58d63)
INFO[0000] | Attach stdin to the container 0adcb13ea525
/bin/sh: 1: [/bin/bash]: not found
```

If I remove the brackets, I have the expected behaviour:

```
INFO[0000] ATTACH '/bin/bash'
INFO[0000] | Created container 658eec692189 (image sha256:58d63)
INFO[0000] | Attach stdin to the container 658eec692189
root@da009f64aa65:/app#
```

The doc is telling that the former is correct, but obviously it is the other one that works.
If the doc must be fixed I can do it, but as I don't know what behavior you expect ... just tell ;)

**Comment by skolsuper** [comment]
Double quotes are required when using json syntax for commands.

**Comment by ybogdanov** [comment]
Thanks, @hartym and @skolsuper!
