### ISSUE TITLE
Colored output and white background

### ISSUE THREAD

**Issue by krlmlr** [grammarly/rocker#136]
My terminal has its background set to white, I'm missing relevant parts of the progress output of `rocker build`.

**Comment by ctrlok** [comment]
@krlmlr do you mean only step coloring? 
I make PR, so now it looks much better. Can you try rocker from my brunch for testing? 

<img width="670" alt="1__vsevolodpolyakov_vsevolods-mbp____projects_tmp_tmp2__zsh_" src="https://cloud.githubusercontent.com/assets/3265316/21466186/720a9316-c9c8-11e6-8d59-d78dc806411e.png">

**Comment by krlmlr** [comment]
Thanks @ctrlok, I haven't been using rocker much lately, but I hope I can benefit from your PR the next time I'm be using it.

**Comment by ybogdanov** [comment]
Thanks for reporting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to address it. Sorry.
