### ISSUE TITLE
All platforms I try to run rocker build on produce this error...

### ISSUE THREAD

**Issue by vroomanj** [grammarly/rocker#140]
panic: Unknown command: un

goroutine 1 [running]:
panic(0x968660, 0xc82019f500)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/grammarly/rocker/src/build.NewCommand(0xc82019e6d0, 0x2, 0xc82019f390, 0x1, 0x1, 0x0, 0xc8201cc390, 0xc8201588c0, 0x91, 0x0, ...)
        /go/src/github.com/grammarly/rocker/src/build/commands.go:121 +0x57f
github.com/grammarly/rocker/src/build.NewPlan(0xc820120a00, 0x2e, 0x43, 0x1, 0xc8200e9c00, 0x2d, 0x40, 0x0, 0x0)
        /go/src/github.com/grammarly/rocker/src/build/plan.go:49 +0x20f
main.buildCommand(0xc8200a6540)
        /go/src/github.com/grammarly/rocker/main.go:394 +0x23a9
github.com/grammarly/rocker/vendor/github.com/codegangsta/cli.Command.Run(0xb60fc0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc3b9c0, 0x2d, 0x0, ...)
        /go/src/github.com/grammarly/rocker/vendor/github.com/codegangsta/cli/command.go:117 +0x1057
github.com/grammarly/rocker/vendor/github.com/codegangsta/cli.(*App).Run(0xc820092e00, 0xc82000a260, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/grammarly/rocker/vendor/github.com/codegangsta/cli/app.go:159 +0xc3e
main.main()
        /go/src/github.com/grammarly/rocker/main.go:233 +0x27ab

**Comment by ybogdanov** [comment]
Hi @vroomanj! Can you provide your Rockerfile please?

**Comment by ccarterc** [comment]
The docs say you need a specific version of GO.  1.5.xx I believe.

**Comment by ybogdanov** [comment]
Thanks for reporting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to address it. Sorry.
