### ISSUE TITLE
Cleanup after build

### ISSUE THREAD

**Issue by mcassaniti** [grammarly/rocker#146]
I've found that rocker will keep intermediate images, containers and volumes when they are used. If I complete a build successfully, I just want the final image and not the pieces in between, even if I do an attach. Can a flag be added that will take options for clean-up?

Options should be:
- on-success: clean-up after a successful build
- always: clean-up regardless of build state
- never (default): Do as rocker currently does (in version 1.3.0)

**Comment by ctrlok** [comment]
As I understand, in Rocker they keep images for caching. 
You want to remove all images, volumes, and containers if the are not tagged in Rockerfile?

**Comment by mcassaniti** [comment]
That is correct. If the most appropriate response is RTFM, I'm sorry but I missed the correct option.

**Comment by ybogdanov** [comment]
Thanks for your question. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this as we are not able to address it. Sorry.
