### ISSUE TITLE
ADD does not honor ownership

### ISSUE THREAD

**Issue by hugochinchilla** [grammarly/rocker#149]
given this example Rockerfile 

~~~
FROM php
USER www-data
ADD foo /foo
~~~

The `/foo` file will be owned by `root` inside the resulting container

**Comment by ybogdanov** [comment]
Thanks for reporting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to address it. Sorry.
