### ISSUE TITLE
Please add windows builds

### ISSUE THREAD

**Issue by withinboredom** [grammarly/rocker#150]
This way, us Windows peoples can be lazy like the OSX peoples and not have to build things from scratch.

Check out appveyor if you need a free environment to build the releases.

Thank you!

**Comment by whitecolor** [comment]
Or at least proper instructions for windows users with concrete build steps) Though build is better of course.

**Comment by michzimny** [comment]
I have built rocker for Windows with:
> docker run --rm -v "$PWD":/usr/src/myapp -e GOPATH=/usr/src/myapp -e GOOS=windows -e GOARCH=amd64 -e GO15VENDOREXPERIMENT=1 golang:1.6 go get -v github.com/grammarly/rocker

then in ./bin/windows_amd64/ I've got rocker.exe.

Before running, the env variable must be set to let rocker connect to docker, in my case (Windows 10 x64, Docker on Hyper-V) it is:
> DOCKER_HOST="tcp://localhost:2375"

However, I experience issues with file paths on Windows. First, the cache directory is "~/.rocker_cache" by default, so it must be manually set on "rocker build" calls with "--cache-dir" option. Next, on building, rocker tries to create directories named like "sha256:0584ab3..." - the colon is not acceptable in Windows paths. This is where I am with this topic. The colon problem should probably be changed in the sources of rocker.

Maybe it helps and someone goes further.

**Comment by matleh** [comment]
Even though I am on MacOS, some of my colleges use Windows. To use Rocker as a development tool within our company, platform independence is crucial.

**Comment by whitecolor** [comment]
@matleh I advice to use "Ubuntu bash for windows" for web dev on windows. You can install docker client there and it will interact with docker for windows host.

**Comment by ybogdanov** [comment]
Thanks for requesting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to implement it. Sorry.
