### ISSUE TITLE
No author in docker image

### ISSUE THREAD

**Issue by dohnto** [grammarly/rocker#154]
### Rocker version
rocker version 1.3.0 - 9444404 (master) 2016-07-20_13:43_GMT

### Steps to reproduce
```bash
# cat Dockerfile 
FROM busybox
MAINTAINER foo
TAG test
# rocker build -f Dockerfile .
...
# docker inspect -f='{{.Author}}' test

#
```

### Expected state
```bash
# docker inspect -f='{{.Author}}' test
foo
```

### Additonal info
The behaviour differs from docker and the state is not documented (at least I have not found it).

Thank you for response

**Comment by ctrlok** [comment]
`MAINTAINER` command will be [deprecated in docker 1.13](https://github.com/docker/docker/pull/25466). Are you sure about it?

**Comment by ybogdanov** [comment]
Thanks for reporting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to address it. Sorry.
