### ISSUE TITLE
Docker for windows: can't build

### ISSUE THREAD

**Issue by whitecolor** [grammarly/rocker#156]
I'm using `docker for windows`, I've build rocker and when I try to run `rocker build` I've got the folliwng error:

```
FATA[0000] Get http://unix.sock/_ping: dial unix /var/run/docker.sock: socket: An address incompatible with the requested protocol was used.
```

**Comment by ctrlok** [comment]
This bug was fixed in https://github.com/fsouza/go-dockerclient/pull/579
So, we need to update go-dockerclient in rocker

**Comment by whitecolor** [comment]
Is it possible to use now?

**Comment by michzimny** [comment]
@whitecolor, how have you installed rocker in Windows? Could you share your experiences in #150?

**Comment by ybogdanov** [comment]
Thanks for requesting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to implement it. Sorry.
