### ISSUE TITLE
Support mount options?

### ISSUE THREAD

**Issue by wied03** [grammarly/rocker#157]
Just did my first build using ```MOUNT``` on an SELinux enabled system. When I try and mount a directory, the SELinux context doesn't match the build container's so I get access denied.

I can workaround this by disabling SELinux during the build but is there any objection to adding support for mount volume options? It looks like it would be a fairly easy change to `CommandMount`.

**Comment by ccarterc** [comment]
Can you set the UID when you perform the `docker run` command?  I had to do something like this when mounting folders using docker not rocker:

`docker run -u $(id -u $(whoami)) -d ...`

It should set the UID within a container to match that of the host.

**Comment by wied03** [comment]
Yes but Im not talking about after I've built the image. I'm talking about
when I'm using rocker to build it.

sent from my mobile device

**Comment by ctrlok** [comment]
@wied03 do you mean something like #161 , but for "MOUNT"?

**Comment by ybogdanov** [comment]
Thanks for requesting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to implement it. Sorry.
