### ISSUE TITLE
Rockerfile is missing while specified by -f

### ISSUE THREAD

**Issue by dmytroleonenko** [grammarly/rocker#165]
When the path to the Rockerfile is specified by -f /path/subdir/Rockerfile
rocker build -f  /path/subdir/Rockerfile .
fails with:
FATA[0000] open /path/Rockerfile: no such file or directory 
pwd is /path

Creating an empty Rockerfile fixes the issue

**Comment by ctrlok** [comment]
@dmytroleonenko you can run rocker command without dot at the end. Try `rocker build -f /path/subdir/Rockerfile`

**Comment by ctrlok** [comment]
@dmytroleonenko are that fix your problem?
