### ISSUE TITLE
label and t args are missing

### ISSUE THREAD

**Issue by dmytroleonenko** [grammarly/rocker#166]
With docker one can build an image with
docker build -t myname:my_ver --label mylabel=myvalue .
rocker binary doesn't any of these

Should be easy to fix I suppose

**Comment by ctrlok** [comment]
You can do it with variables. 

```bash
☁  cat Rockerfile
FROM ubuntu
RUN apt-get update
LABEL {{ .myLabel }}
TAG {{ .myTag }}%                                                                                                                           

# Just printing file whithout build
☁  rocker build --var myLabel="LABEL test" --var myTag=some:version --print
FROM ubuntu
RUN apt-get update
LABEL LABEL test
TAG some:version%
```

I think that way is much more cleaner that docker way, but we can discuss about feature parity of `docker build`.

**Comment by bendikro** [comment]
Supporting this makes transitioning to Rocker much easier.

**Comment by ybogdanov** [comment]
Thanks for requesting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to implement it. Sorry.
