### ISSUE TITLE
Support --cache-from

### ISSUE THREAD

**Issue by withinboredom** [grammarly/rocker#167]
Docker 1.13 introduces --cache-from ... it would be really cool if a PUSH or TAG would automatically use the same system while building.

ie.

```
FROM something
RUN xyz
PUSH something/else:latest
```

The push would tell rocker/docker to cache from `something/else:latest` when it hits the `FROM`

**Comment by ybogdanov** [comment]
Thanks for requesting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to implement it. Sorry.

**Comment by ybogdanov** [comment]
And it's a cool idea, by the way :)
