### ISSUE TITLE
Google Cloud Registry does not support listing tags and fails pulling images

### ISSUE THREAD

**Issue by fiji-flo** [grammarly/rocker#174]
Like ECR, GCR does not support listing tags. A minimal change would look like [this](https://github.com/fiji-flo/rocker/commit/0d1518fc1c92a80ab077767ba269093099c10215).

Any chance to this merged?

**Comment by ybogdanov** [comment]
Thanks for requesting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to implement it. Sorry.
