### ISSUE TITLE
Using ENV vars in MOUNT command

### ISSUE THREAD

**Issue by vjpr** [grammarly/rocker#175]
I don't seem to be able to use ENV vars in the MOUNT command.

Environment replacement works with VOLUME, etc. in normal Dockerfile. I would expect it to work in Rocker MOUNT.

https://docs.docker.com/engine/reference/builder/#environment-replacement

**Comment by ybogdanov** [comment]
Thanks for reporting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to address it. Sorry.
