### ISSUE TITLE
CMD doesn't respect dockerfile syntax, needs to be used as in the command line

### ISSUE THREAD

**Issue by tanty** [grammarly/rocker#176]
My Rockerfile has:

...
CMD ["/bin/sh", "-c", "echo hello"]
...

And fails with:

/bin/sh: 1: [/bin/sh,: not found

However, it works if I write:

...
CMD "/bin/sh" "-c" "echo hello"
...

**Comment by ybogdanov** [comment]
Thanks for reporting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to address it. Sorry.
