### ISSUE TITLE
ADD command on macos doesn't set root uid/gid

### ISSUE THREAD

**Issue by JGiard** [grammarly/rocker#179]
According to https://docs.docker.com/engine/reference/builder/#add
when adding a file the uid/gid should be 0

the following Dockerfile when run produces the expected output
```
FROM python:3.5
ADD foo /foo
CMD ls -al /foo
```
> touch foo && docker build -t foo . && docker run -it foo
-rw-r--r-- 1 root root 0 Jul 24 13:44 /foo

however the following Rockerfile mess-up permissions
```
FROM python:3.5
ADD foo /foo
CMD ls -al /foo
TAG bar
```
> touch foo && rocker build -f Rockerfile && docker run -it bar
-rw-r--r-- 1 501 dialout 0 Jul 24 13:44 /foo

I'm using docker 17.06.0-ce and rocker 1.3.1

Thank you for your help

**Comment by ybogdanov** [comment]
Thanks for reporting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to address it. Sorry.
