### ISSUE TITLE
Support Insecure-Private Registry's

### ISSUE THREAD

**Issue by hjanuschka** [grammarly/rocker#181]
sadly we have to use a insecure private registry. however `https` is hardcoded in https://github.com/grammarly/rocker/blob/master/src/dockerclient/registry.go#L81

however as i am currently unable to build locally - i am not really able to do a PR (#180)

any chances for insecure registry support?

like `rocker build --force-insecure`

**Comment by ybogdanov** [comment]
Thanks for requesting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to implement it. Sorry.
