### ISSUE TITLE
Use template to loop over glob outputs.

### ISSUE THREAD

**Issue by TMaYaD** [grammarly/rocker#183]
I would like to use something like this:

```
FROM alpine:latest

#Do something here

TAG base:latest

{{ range $folder := (For each directory in /utils/*) }}
  FROM base:latest

  ADD {{ $folder }}/ /workdir

  TAG util-{{ trimPrefix $folder "/utils/" }}:latest
{{ end }}
```

Is it possible?

**Comment by TMaYaD** [comment]
Ideally we should be able to load any shell command output so that I could do `{{ $version := exec "git rev-parse --short HEAD" }}`

**Comment by ybogdanov** [comment]
Thanks for requesting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to implement it. Sorry.
