### ISSUE TITLE
Rocker build --network

### ISSUE THREAD

**Issue by kpramesh2212** [grammarly/rocker#186]
Hi Team,

Could you please let me know is there any facility or feature that can help with communicating with existing container during build

docker equivalent is to use 
docker build -f dockerfile --network='isolated_nw'

So basically what I would want to do is

1. Build an image which basically installs a product A.

2. During install of Product A it should communicated with database A which is running in another container

3. Finally commit the image (Product A install Image)

Could you please help me here please.

Regards
Ramesh

**Comment by ybogdanov** [comment]
Thanks for requesting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to implement it. Sorry.
