### ISSUE TITLE
Implement HEREDOC functionality from Dockramp

### ISSUE THREAD

**Issue by Tzrlk** [grammarly/rocker#187]
A pretty awesome feature introduced by dockramp was HEREDOC support at the least during execution of RUN statements. While this can be dealt with by mounting a scripts directory, having it in the build file made it much easier to read what was going on.

**Comment by ybogdanov** [comment]
Thanks for requesting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to implement it. Sorry.
