### ISSUE TITLE
EXPORT fails

### ISSUE THREAD

**Issue by splitbrain** [grammarly/rocker#188]
When I have an EXPORT statement in my Rockerfile, the build fails:

    Failed to check image grammarly/rsync-static:1, error: API error (500): {"message":"Get https://registry-1.docker.io/v2/grammarly/rsync-static/manifests/1: unauthorized: incorrect username or password"}

**Comment by ybogdanov** [comment]
Thanks for reporting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to address it. Sorry.
