### ISSUE TITLE
SHELL command is not supported by Rocker

### ISSUE THREAD

**Issue by BrannonKing** [grammarly/rocker#191]
Dockerfile allows you to override the default shell through use of the SHELL command. However, Rocker pukes on this command saying it is unsupported. See https://docs.docker.com/engine/reference/builder/#shell

**Comment by ybogdanov** [comment]
Thanks for requesting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to implement it. Sorry.
