### ISSUE TITLE
Unit tests fail with go 1.10

### ISSUE THREAD

**Issue by mklimuk** [grammarly/rocker#196]
Go 1.10 brings some refactoring in `archive/tar` package. It causes several rocker unit tests to fail. Apparently it comes from this fragment of `build/copy.go` (line 141):

`if _, err = io.Copy(ioutil.Discard, tarSum); err != nil {
	return s, err
}`

The problem occurs in tar writer's Close()/Flush() method. Not sure how to tackle it though. If I ignore the error everything works fine but it is not an acceptable solution of course.

**Comment by ybogdanov** [comment]
Thanks for reporting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to address it. Sorry.
