### ISSUE TITLE
Would be nice to get results of `rocker show` in creation time order

### ISSUE THREAD

**Issue by slevental** [grammarly/rocker#25]
I need to retrieve last N images to get the most recent version I've pushed
Optional parameter N would be great too, anyway chronological order will allow to use standard linux tools - head/tail

**Comment by ybogdanov** [comment]
N is useful when you have too many images, it might take a lot of time to fetch.
PR!

**Comment by ybogdanov** [comment]
The feature is deprecated in Rocker v1.
