### ISSUE TITLE
do not create .rockerignore for user

### ISSUE THREAD

**Issue by chernetsov** [grammarly/rocker#27]
in many cases there is no need in this file (when ./ is not being ADDed)
rocker is being too intrusive here

reporting warns is OK

**Comment by ybogdanov** [comment]
Fixed on the [new rocker already](https://github.com/grammarly/rocker/tree/v1#note-on-v1-branch). You can start use it now, few people are already testing it and it works well for them. It will be merged to master this week.

**Comment by chernetsov** [comment]
@ybogdanov awesome, thanks!
