### ISSUE TITLE
[feature request] add hooks support

### ISSUE THREAD

**Issue by missedone** [grammarly/rocker#3]
hi folds
in my project, we normally need to build the web application package with command line (e..g for java web app, using 'mvn -e clean install') before build the docker images
so there are two command lines to accomplish the job:
1. build web application
2. build images
though i can simply wrap them into bash script, or makefile or any other build tool. I think now that Rocker is a nice build tool, why not span the lifecycle to support 'pre-build', 'post-build', for example, in 'pre-build' phase, we can run command line to build the web application first, and copy deliverables to the folder of Rockfile so that we can copy them into the image.

thanks

**Comment by ybogdanov** [comment]
Hi @missedone,

As we noted in the recent [blog post](http://tech.grammarly.com/blog/posts/Making-Docker-Rock-at-Grammarly.html):

> You can build the artifact on a CI server and then put to the docker image; in this case you can keep your resulting image clean. But then you lose the advantages of build environment portability and isolation between different versions of software. Also, it is more error-prone, because you cannot test your builds locally.

We found it more convenient to move all build-specifics to Dockerfiles as well. Rocker itself provides great primitives to do so. It is one of the reasons why Rocker was invented, to be clear.

Also, it will expose Rockerfiles to the host system and will provide arbitrary script execution. Which I'm not sure how to treat.

Can you explain why you cannot build your deliverables right in the Rockerfile?

**Comment by missedone** [comment]
yeah, i got your idea, in Rocker's philosophy is to accomplish the application build in Docker as well, then pass the deliverable to next Docker image.
however, in my env, i think it might be a too big step forward, i'd like think more about it and experiment a little bit.
one same concern is we build the app with maven which will download a lot dependent artifacts from nexus repo, even i can persist most of them in the docker image, still it would take a lot of time to download the snapshot artifacts next time.

**Comment by ybogdanov** [comment]
@missedone take a look at the recent blog post about rocker http://tech.grammarly.com/blog/posts/Making-Docker-Rock-at-Grammarly.html

Actually, the initial point of Rocker invention was to solve the "maven" issue.

**Comment by missedone** [comment]
right, i was thinking in my old way, not rocker way.
thanks

**Comment by missedone** [comment]
right, i was thinking in my old way, not rocker way.
thanks
