### ISSUE TITLE
When using mounts one is basically forced to --no-cache

### ISSUE THREAD

**Issue by bobef** [grammarly/rocker#32]
Just my use case... I use MOUNT to put common dependencies in the projects, without copying them everywhere, only inside the image. This means I rebuild the images mostly to update the dependencies. But caching doesn't work for mounts so I need to --no-cache for every build. Caching for mounts would be really cool. Right now it would be cheaper for me to copy the dependencies in the project and build with docker, because copying takes 1 or 2 seconds and --no-cache takes a lot more.

**Comment by ybogdanov** [comment]
Hi @bobef. You are talking about `MOUNT` cache invalidation, I was thinking many times about how to implement it, but it doesn't seem to be an easy one. The easiest way to invalidate `MOUNT` is to trigger commands that are "side-effecting" to it:

```Dockerfile
MOUNT ...
ENV v=1
RUN do something that writes to a mounted directory
```

By changing `ENV` you will trigger the invalidation of `RUN`, which will update the contents of a mounted directory.

But I'm not sure this is overall the best way to achieve what you want. Can you clarify your use case so maybe I can suggest a cleaner solution?

> I use MOUNT to put common dependencies in the projects, without copying them everywhere, only inside the image.

Can you provide some example of Rockerfiles you have?

**Comment by bobef** [comment]
Hi Yuriy. I have only one Rockerfile so far. My use case is this. I have N applications which all use the same framework and they are very framed. Basically they don't need separate Dockerfile. So I just have a base Dockerfile with lots of ONBUILD that will execute in each application's context [directory] and create a different image and the Dockerfile of the applications just say "FROM baseimage". But the problem is all these apps use the same framework which needs to go in the image. Copy pasting it in 20 directories is not so nice, so I want to mount it externally and that's what I tried to achieve with my Rockerfile. Here is the Rockerfile. I use it the same way I described above. It is shared for all applications, there is no per-application Rockerfile. I just mount different application sources and the framework and I copy them. But without cache for the mounts I need to do --no-cache all the time which is not cool. Also I need to RUN rm a lot of stuff because .dockerignore is not used this way. So I resorted to temporarily copying the framework inside application context directory before build and removing it later, but this is probably not a final solution.

```dockerfile
FROM debian:jessie
MAINTAINER Borislav Peev (borislav.asdf at gmail dot com)

COPY *.conf /volume/config/nginx/

REQUIRE [ "project_local", "project_providerkit" ]
MOUNT {{.project_local}}:/mounts/app
MOUNT {{.project_providerkit}}:/mounts/providerkit
RUN cp -R /mounts/app /
RUN cp -R /mounts/providerkit /app/lib/
RUN rm -rf /app/.git
RUN rm -rf /app/lib/providerkit/.git
RUN rm -rf /app/lib/providerkit/docs
RUN rm -rf /app/lib/providerkit/examples
RUN rm -rf /app/lib/providerkit/modules/core/.git
RUN rm -rf /app/lib/providerkit/modules/core/docs
RUN rm -rf /app/lib/providerkit/modules/core/examples
RUN rm -rf /app/lib/providerkit/modules/core/tests
RUN rm -rf /app/lib/providerkit/modules/supplier/examples
RUN rm -rf /app/lib/providerkit/modules/supplier/tests
RUN rm -rf /app/lib/providerkit/modules/supplier/skeleton
RUN rm -rf /app/lib/providerkit/modules/logging/.git
RUN rm -rf /app/lib/providerkit/modules/logging/examples

# copy cron jobs for the provider, if any
RUN mkdir -p /volume/cron
RUN cp -R /app/docker/*-cron /volume/cron/ | true
RUN cp -R /app/lib/providerkit/docker/*-cron /volume/cron/
RUN chmod 0644 /volume/cron/*-cron
RUN ln -sf /app/store/log/cron.log /volume/cron/cron.log

# load providerkit-php from lib
RUN sed -i -r 's|\.\./\.\./\.\./providerkit-php/[^/]+/|lib/providerkit-php/|' /app/supplier.php

# load common config from the same dir
RUN sed -i -r "s| \. '/../../_common'||" /app/config.php


# this is so we can mount this in the php and nginx containers
VOLUME /app
VOLUME /volume/cron
VOLUME /volume/config/nginx

# just wait forever
CMD [ "sleep", "infinity" ]

REQUIRE [ "image", "tag" ]
TAG {{.image}}:{{.tag}}
```

**Comment by ybogdanov** [comment]
@bobef just to clarify, why you cannot use COPY for that?

**Comment by bobef** [comment]
Because the dir tree is like this:
```
/apps/providerkit
/apps/app1
/apps/app2
```

To use copy I need to do `docker build -f apps/app1/Dockerfile /apps`, i.e. execute docker in the top directory and not in each applications directory, so it will be able to copy from everywhere, which is not so nice because I don't want to bind the Dockerfile to the specific directory structure.

**Comment by ybogdanov** [comment]
Can you make `providerkit` the base image for all apps?

**Comment by bobef** [comment]
I can, but each app already have 3 containers - nginx, php, the app sources. This would add 4th container. So ~20x4 is 80 containers in docker ps, not so nice, so I prefer to spare this one here.

**Comment by bobef** [comment]
Oh, sorry, I misinterpreted. Yes, base image, ...yes that would probably work. I didn't thought of putting it in the base image.

**Comment by ybogdanov** [comment]
providerkit base image:

```Dockerfile
FROM debian:jessie
ADD . /app/lib/
TAG providerkit
```

app image:

```Dockerfile
FROM providerkit
ADD . /app/
```

**Comment by bobef** [comment]
@ybogdanov Thanks for the tip :) I'll do that.

**Comment by ybogdanov** [comment]
Let me know when you succeeded.

**Comment by bobef** [comment]
Well, at least because I didn't have this idea and wanted to solve it with MOUNTs, I added support for rocker in my deploy tool, so now it uses both rocker and rocker-compose ;) Thanks again for the great tools you are sharing with us.

**Comment by ybogdanov** [comment]
Thanks, @bobef!
