### ISSUE TITLE
how to def default value in template

### ISSUE THREAD

**Issue by missedone** [grammarly/rocker#38]
hi folks

i have following line in the Rockerfile that want to define the default value for HTDOCS_DIR:
```
MOUNT {{ .HTDOCS_DIR "/opt/htdocs" }}:/tmp/htdocs
```

but i got error below:
```
2015/10/03 08:51:47 Error executing template /home/nick/dev/test/Rockerfile, error: template: /home/nick/dev/test/Rockerfile:5:9: executing "/home/nick/dev/test/Rockerfile" at <.HTDOCS_DIR>: HTDOCS_DIR is not a method but has arguments
```

remove the default value "/opt/htdocs" then rocker build works with -var HTDOCS_DIR=/opt/htdocs.

so i'm wondering does it support default value here?
thanks

**Comment by ybogdanov** [comment]
```
MOUNT {{ or .HTDOCS_DIR "/opt/htdocs" }}:/tmp/htdocs
```

**Comment by missedone** [comment]
thanks, is there any complete referent about how to use template here? e.g. the syntax, etc.

**Comment by ybogdanov** [comment]
https://github.com/grammarly/rocker/tree/master/src/rocker/template

**Comment by missedone** [comment]
great, thanks
