### ISSUE TITLE
EXPORT/IMPORT is not working with Docker 1.9: rsync-static container volumes

### ISSUE THREAD

**Issue by ybogdanov** [grammarly/rocker#51]
There is a problem appeared due Docker 1.9 new volumes behavior. The volume is present, but there is no `rsync` static binary there (as it is in [rsync-static image](https://github.com/grammarly/rocker/blob/master/rsync/Rockerfile#L31))

You might recognize this error if you ever had the following with Rocker v1 and Docker 1.9:

```
ERRO[0265] exec: "/opt/rsync/bin/rsync": stat /opt/rsync/bin/rsync: no such file or directory 
```

See also #8 for a relevant discussion.

**Comment by ybogdanov** [comment]
Ok, I found the problem.
Rocker uses a transient container for running rsync command that copies desired files from the layer to the exports container. After copy operation is done it deletes the temporary container https://github.com/grammarly/rocker/blob/501e0856806df59ad7d50165a48e123ef66c9b0a/src/rocker/build/commands.go#L1246

At the same time, client has a functionality to clean the volumes from all removed containers, so there is no garbage left https://github.com/grammarly/rocker/blob/501e0856806df59ad7d50165a48e123ef66c9b0a/src/rocker/build/client.go#L362
And this is a clearly appropriate behavior.

What is inappropriate is that Docker 1.9 started to remove also volumes of an attached container as well:

Consider container `A[volumes:/foo]` and container `B[volumes-from:A]`. If we remove B, then volumes of A would be also removed. Seems like a Docker bug.

**Comment by ybogdanov** [comment]
Trying to reproduce the issue outside of Rocker, but seems to be legit by now:

```
docker run --name volumes_test -v /data alpine:3.2 touch /data/file

docker run --name volumes_test_cli1 --volumes-from volumes_test alpine:3.2 ls /data/file
docker rm -fv volumes_test_cli1

docker run --name volumes_test_cli2 --volumes-from volumes_test alpine:3.2 ls /data/file
docker rm -fv volumes_test_cli2

docker rm volumes_test
```

Both `volumes_test_cli1` and `volumes_test_cli2` see the `/data/file` despite `cli1` has been removed with `-v` flag.

**Comment by fxposter** [comment]
:+1:

**Comment by ybogdanov** [comment]
How I solved it:

Instead of doing `A[volumes:/foo]` and `B[volumes-from:A]` I inspect the `A`, take mounts information and then *bind* the full paths of `A` volume directories into `B`. So there is no `volumes-from` anymore.

In the future, we might lock Rocker on Docker >= 1.9 and use volumes API instead of creating old fashioned volume containers.

**Comment by fxposter** [comment]
Yep, I've checked the changes :) and 1.0.1 works fine for me, thanks!
