### ISSUE TITLE
Rocker binary 1.1.0 on linux does not work (1.0.1 ok)

### ISSUE THREAD

**Issue by sebest** [grammarly/rocker#71]
Hello,

i get the following error with the binary version 1.1.0 on Linux when i run rocker build:
FATA[0000] invalid character '}' after top-level value
Even with an empty Rockerfile

version 1.0.1 is working fine

**Comment by ybogdanov** [comment]
Hi @sebest, thanks for reporting. It's a cache problem. You can easily get rid of this problem my removing cache directory at `~/.rocker_cache`. Have you tried uploading images to S3?

**Comment by ybogdanov** [comment]
If you tried S3 it can be the cause. Then, you can keep the cache and remove just `~/.rocker_cache/_digests` directory and see if it start working.

**Comment by sebest** [comment]
Hi @ybogdanov ,

Thanx for helping!

I've never tried to upload to S3, i tried `rm -rf ~/.rocker_cache/` but it did not fix the problem :(

**Comment by sebest** [comment]
I did a strace and it seems to be related to `/root/.docker/config.json`

**Comment by sebest** [comment]
My config.json was invalid JSON.
