### ISSUE TITLE
MOUNT: more informative error message about relative paths usage for volume mounts

### ISSUE THREAD

**Issue by thedrow** [grammarly/rocker#72]
It will help keeping the environment consistent between developers operating systems and the CI.

**Comment by thedrow** [comment]
Sorry it works but the error message is not clear.
I got 
```
Failed to create container rocker_mount_454849558b6a from image grammarly/scratch:latest, error: API error (500): evalSymlinksInScope: /mnt/sda1/var/lib/docker/aufs/mnt/cache/apt is not in /mnt/sda1/var/lib/docker/aufs/mnt/aabcaeab9dfc631704b13494d6f82f082a597bb3351e163a5dd34523748e0e95
```
For ```MOUNT ../cache /var/cache/apt/```
I should have used For ```MOUNT ../cache:/var/cache/apt/```

**Comment by ybogdanov** [comment]
Yep, will make error message more informative, thanks!
