### ISSUE TITLE
Allow to unmount mounted volumes

### ISSUE THREAD

**Issue by thedrow** [grammarly/rocker#73]
I'm using MOUNT to store cached Debian packages for faster build times.
In order to reduce the container size I'd like to remove those packages from the container after I'm done but removing them will remove them from the mounted directory as well.
An UNMOUNT command will assist in that aspect because I'll be able to delete the cached packages from the container without deleting them from the mounted directory.

**Comment by ybogdanov** [comment]
Can you please give a simplified Rockerfile of your case?

**Comment by thedrow** [comment]
```dockerfile
FROM me/base:layer2
MAINTAINER "Omer Katz <omer.drow@gmail.com>"

MOUNT ../cache/ccache:/root/.ccache
MOUNT ../cache/apt:/var/cache/apt
MOUNT ../cache/apt-lists:/var/lib/apt/lists

RUN apt-get update && apt-fast install python-dev libpcre3-dev -y

RUN curl -SL https://github.com/jemalloc/jemalloc/releases/download/4.0.4/jemalloc-4.0.4.tar.bz2 | tar -jxf -

RUN cd jemalloc-4.0.4 && ./autogen.sh --prefix /usr && make -j 4 && make -j 4 install

ENV UWSGI_MALLOC_IMPLEMENTATION=jemalloc

RUN pip install --disable-pip-version-check uwsgi==2.0.12
RUN uwsgi --show-config || echo OK

CMD uwsgi
ENTRYPOINT uwsgi

# proposed syntax
UNMOUNT /root/.ccache
UNMOUNT /var/cache/apt
UNMOUNT /var/lib/apt/lists

RUN rm -R /root/.ccache/ && rm -R /root/cache/apt/ && rm -R /var/lib/apt/lists

TAG me/uwsgi:latest
TAG me/uwsgi:2.0.12
```

**Comment by ybogdanov** [comment]
The data that is on mounted volumes or host machine directories is not going to the image. In other words, you don't need `UNMOUNT` and `RUN rm...` because the files under `/root/.ccache` are not in your image anyway. The files are on your host machine.

**Comment by elifarley** [comment]
In other words, the MOUNT command is in effect during the build only.

When running your image, everything works as if the MOUNT command didn't exist at all.

Am I right?

**Comment by romank87** [comment]
@elifarley yes, that's right

**Comment by thedrow** [comment]
Nevertheless, it would still be useful to be able to unmount a directory during build time.

**Comment by ybogdanov** [comment]
I don't see any sense, sorry.

**Comment by titpetric** [comment]
I'd add a different use case, for example:

https://community.c9.io/t/how-to-install-a-deb-package/5007/2

You could mount a folder with .deb files into `/var/cache/apt/archives', use apt-get install, and then unmount this folder so you can do the standard `apt-get update` && installs and such.
