### ISSUE TITLE
ADD url does not work

### ISSUE THREAD

**Issue by missedone** [grammarly/rocker#80]
hi folks

in my Rockerfile, there is ADD directive to retrieve the file from remote:

```Dockerfile
FROM centos:7

ADD http://mirrors.163.com/.help/CentOS6-Base-163.repo /opt/pkg/CentOS6-Base-163.repo
RUN ls -a /opt/pkg/CentOS6-Base-163.repo
```

but looks like ADD url does not work any more (i remember this worked long time ago)

```
localhost $ rocker build
INFO[0000] FROM centos:7
INFO[0000] | Image sha256:61b44                          size=196.6 MB
INFO[0000] ADD http://mirrors.163.com/.help/CentOS6-Base-163.repo /opt/pkg/CentOS6-Base-163.repo
INFO[0000] | No files matched
INFO[0000] RUN ls -a /opt/pkg/CentOS6-Base-163.repo
INFO[0000] | Not cached
INFO[0000] | Created container 16e3370d1fa5 (image sha256:61b44)
ls: cannot access /opt/pkg/CentOS6-Base-163.repo: No such file or directory
INFO[0000] | Removing container 16e3370d1fa5
FATA[0000] Container 16e3370d1fa5 exited with code 2
```

i'm using Rocker 1.1.2 release, 
the same issue with latest changes on master branch built on my local

**Comment by missedone** [comment]
PS, i need this ADD url is because at the very early stage of the build time, we even don't have curl or wget installed, hence i rely on ADD to download the remote file into the image.

if i run with docker build (docker client/server 1.10.3), the ADD works

```
docker build .
Sending build context to Docker daemon 3.072 kB
Step 1 : FROM centos:7
 ---> 61b442687d68
Step 2 : ADD http://mirrors.163.com/.help/CentOS6-Base-163.repo /opt/pkg/CentOS6-Base-163.repo
Downloading 2.006 kB/2.006 kB
 ---> 578a84beae29
Removing intermediate container 36ea08cc6578
Step 3 : RUN ls -a /opt/pkg/CentOS6-Base-163.repo
 ---> Running in 3c0c90c6b592
/opt/pkg/CentOS6-Base-163.repo
 ---> 165124f89844
Removing intermediate container 3c0c90c6b592
Successfully built 165124f89844
```

**Comment by romank87** [comment]
Yes, it's known limitation and we are about to do it in future versions.
Please find `ADD <url>` in README

**Comment by diunko** [comment]
fixed in https://github.com/grammarly/rocker/pull/91

**Comment by missedone** [comment]
cool, verified with pr #91 on my local
thanks

BTW, do you have any plan to support auto extract tar file with ADD?

**Comment by missedone** [comment]
oh, please remember to update the README, ADD \<url\> now supported
> What is not supported yet:
ADD \<url\>
Adding tar archives that supposed to automatically extract
