### ISSUE TITLE
Variable substitution doesn't work inside ONBUILD

### ISSUE THREAD

**Issue by elifarley** [grammarly/rocker#81]
In base/Rockerfile, I have:

```
ENV _USER app
ONBUILD COPY my-file /$_USER/
TAG elifarley/base:latest
```
In child/Rockerfile:
```
FROM elifarley/base:latest
```
When I run rocker build -f child/Rockerfile and then docker run [...], **my-file** can be found at **/\$_USER**

However, when I was using plain docker to build my images, **my-file** ended up at **/app**, as expected.

**Comment by diunko** [comment]
fixed in https://github.com/grammarly/rocker/pull/90
