### ISSUE TITLE
{{ .VAR_NAME }} is resolved too early when inside ONBUILD

### ISSUE THREAD

**Issue by elifarley** [grammarly/rocker#82]
In base/Rockerfile, I have:

```
ONBUILD MOUNT {{ .SSH_PRIVATE_KEY }}:/root/.ssh/id_rsa
TAG elifarley/base:latest
```
In child/Rockerfile:
```
FROM elifarley/base:latest
```

Now, let's build the images:
```
rocker build -f base/Rockerfile --var SSH_PRIVATE_KEY=~user_base/.ssh/id_rsa
rocker build -f child/Rockerfile --var SSH_PRIVATE_KEY=~user_child/.ssh/id_rsa
```

When running elifarley:child, I'd expect to have ~user_child/.ssh/id_rsa mounted in my container, but what I get is ~user_base/.ssh/id_rsa

**Comment by romank87** [comment]
@elifarley  Please think about templating as about preprocessing.
Rocker renders template at first and only then it executes instructions. Thus, it's not possible to implement behavior you are asking for.
