### ISSUE TITLE
How to delete remaining images

### ISSUE THREAD

**Issue by SiriusRed** [grammarly/rocker#83]
Hi, guys!

Whether there is a option whereby deleting all images except the last image specified in Rokerfile.

my Rockerfile:

```
FROM node:onebuild

MOUNT .:/src
WORKDIR /src
RUN npm install

FROM node:slim

ENV SVC_PATH /var/service

COPY . $SVC_PATH

CMD cd $SVC_PATH && node app

EXPOSE 8082

TAG test/test:0.1
```

Image node:onebuild stayed stored.

How delete images after `rocker build` ?

**Comment by romank87** [comment]
stored where? Could you please explain your problem in more details?

**Comment by SiriusRed** [comment]
Run `rocker build` in Rockerfile contains directory, and after successfully build run `docker images`:

REPOSITORY     TAG                 IMAGE ID                CREATED             SIZE
test/test                 0.1               2368127edc21        4 minutes ago       256 MB   # <-------My image
<none>              <none>          3c290695aa48        4 minutes ago       757 MB 
node                     slim              e086d2ed1534        31 hours ago        207.3 MB
node                  onbuild           ebb874bb3ce7        31 hours ago        644.3 MB

 How to delete this image 3c290695aa48  automatically after building?

**Comment by ybogdanov** [comment]
@SiriusRed try `rocker build -no-garbage`
